name: PRの作成
description: 新たなPRを作成する
title: ""
body:
  - type: input
    id: what-changed
    attributes:
      label: 実装内容
      placeholder: 例) cards.tsxのtypoを修正した
    validations:
      required: true
  - type: input
    id: relation-issue
    attributes:
      label: 関連issue
      placeholder: 例) #15
    validations:
      required: false
  - type: textarea
    id: especially-point
    attributes:
      label: 特にみて欲しい部分
      multiple: true
    validations:
      required: false
  - type: textarea
    id: future-tasks
    attributes:
      label: 未実装の部分
      multiple: true
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: 補足
      multiple: true
    validations:
      required: false