name: Issueの作成
description: 必要な修正・付けたい機能などから新たなissueを作成
title: ""
body:
  - type: input
    id: main-page
    attributes:
      label: 作業ページ
      placeholder: 例) cards.tsx
    validations:
      required: true
  - type: textarea
    id: what-needed
    attributes:
      label: 必要な作業内容
      multiple: true
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 補足
      multiple: true
    validations:
      required: false