import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/AllCards.module.css'
import Header from '@/conponents/Header'
import DisplayCard from '@/conponents/Card'
import PrimaryBtn from '@/conponents/PrimaryBtn'
import router from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Index() {

  const data = {
    id: "id",
    name: "ゆうか",
    organization: "watnow",
    x: "chocolatbrown",
    instagram: "yuka__matcha",
    others: "https://my-portfolio-yukachoco.vercel.app",
    urlEnabled: true,
    textColor: "#A56A7F",
    bgColor: "#F4EBEF",
    onClickHandler: () => { },
  }
  return (
    <>
      <Head>
        <title>Who!</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <Link href="/" className={styles.link}>ホーム</Link> */}
        <Header useMenuIcon />

        <div className={styles.cardlist}>
          <DisplayCard
            {...data}
            onClickHandler={() => router.push("/make/card")}
          />
        </div>
        <div className={styles.returnbutton}>
          <PrimaryBtn text={'ホームに戻る'} onClick={() => router.push("/cards")} />
        </div>
      </main>
    </>
  )
}
