import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Index.module.css'
import Link from 'next/link'
import Header from '@/conponents/Header'

const inter = Inter({ subsets: ['latin'] })

export default function Index() {
  const cardid = "card-test"
  return (
    <>
      <Head>
        <title>Who!</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header
          useSearchIcon
          useMenuIcon
          onClick_edit={() => { }}
          onClick_register={() => { }}
        />
        <Link href="/" className={styles.link}>ホーム</Link>
        <Link href="/cards" className={styles.link}>名刺一覧</Link>
        <Link href="/mycards" className={styles.link}>自分の名刺一覧</Link>
        <Link href={`/card/${cardid}`} className={styles.link}>名刺詳細</Link>
        <Link href={'/make/card'} className={styles.link}>名刺作成</Link>
        <Link href={'/make/mycard'} className={styles.link}>他人の名刺作成</Link>
        <Link href={`/share?id=${cardid}`} className={styles.link}>名刺交換</Link>
        <Link href={'/upgrade'} className={styles.link}>課金</Link>
        <Link href={'/warning'} className={styles.link}>警告</Link>
        <Link href={'/error'} className={styles.link}>エラー</Link>
      </main>
    </>
  )
}
