import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Index.module.css'
import Link from 'next/link'
import type { Cards } from '@/types/Cards'
import SinpleButton from '@/conponents/SimpleButton'

const inter = Inter({ subsets: ['latin'] })

export default function Index() {
  const cardid = "test"
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Link href="/login" style={{ backgroundColor: 'white', width: '70%', height: '30px' }}>Login</Link>
        <Link href="/cards" style={{ backgroundColor: 'white', width: '70%', height: '30px' }}>名刺一覧</Link>
        <Link href={`/cards/${cardid}`} style={{ backgroundColor: 'white', width: '70%', height: '30px' }}>名刺一覧</Link>
      </main>
    </>
  )
}
