import Head from 'next/head';
import router from 'next/router';
import Header from '@/components/Header';
import styles from '@/styles/loading.module.css';

export default function Index() {
  return (
    <>
      <Head>
        <title>Who!</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Header useSearchIcon useMenuIcon onClick_edit={() => {}} onClick_register={() => {}} />
        <div className={styles.alldisplay} onClick={() => router.push('/cards')}></div>
        <div className={styles.wrapper}>
          <div className={styles.circle}>
            <p>W</p>
          </div>
          <div className={styles.circle}>
            <p>h</p>
          </div>
          <div className={styles.circle}>
            <p>o</p>
          </div>
          <div className={styles.circle}>
            <p>!</p>
          </div>
          <div className={styles.shadow}></div>
          <div className={styles.shadow}></div>
          <div className={styles.shadow}></div>
          <div className={styles.shadow}></div>
          <span>Loading</span>
        </div>
      </main>
    </>
  );
}
