import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Mycards.module.css'
import Link from 'next/link'
import Header from '@/conponents/Header'
import Card from '@/conponents/Card'
import DisplayCard from '@/conponents/Card'
import MakeNewCard from '@/conponents/NewCard'
import PrimaryBtn from '@/conponents/PrimaryBtn'

const inter = Inter({ subsets: ['latin'] })

export default function Index() {
  const cardid = "card-test"
  return (
    <>
      <Head>
        <title>Who!</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <Link href="/" className={styles.link}>ホーム</Link> */}
        <Header useMenuIcon />

        <div className={styles.cardlist}>
          <DisplayCard
            id={"1"}
            name={"焼肉太郎"}
            organization={"焼肉モリモリクラブ"}
            x={"yakinikuumai"}
            instagram={"yakiyaki"}
            others={"xxx"}
            urlEnabled={false}
            textColor={"#000"}
            bgColor={"#FFF"}
            onClickHandler={() => { }}
          />
          <MakeNewCard />
        </div>
        <div className={styles.returnbutton}>
          <PrimaryBtn text={'ホームに戻る'} />
        </div>
      </main>
    </>
  )
}
