import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/upgrade.module.css';
import Header from '@/conponents/Header';
import PrimaryButton from '@/conponents/PrimaryButton';
import SecondaryButton from '@/conponents/SecondaryButton';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export default function Index() {
  const cardid = 'card-test';
  return (
    <>
      <Head>
        <title>Who!</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Header />
        <div>
          <h2 className={styles.text}>これ以降の機能は課金してね💖</h2>
        </div>
        <div className={styles.Button_wrapper}>
          <Link href='/warning'>
            <SecondaryButton text='課金して始める' onClick={() => console.log('PrimaryButton Clicked')} />
          </Link>
          <Link href='/cards'>
            <PrimaryButton text='戻る' onClick={() => console.log('PrimaryButton Clicked')} />
          </Link>
        </div>
      </main>
    </>
  );
}
