import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Warning.module.css'
import Link from 'next/link'
import Header from '@/conponents/Header'
import router from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Index() {
  const cardid = "card-test"
  return (
    <>
      <Head>
        <title>Who!</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header
          useSearchIcon
          useMenuIcon
          onClick_edit={() => { }}
          onClick_register={() => { }}
        />
        <div className={styles.alldisplay} onClick={()=>router.push("/cards")} >
          <h2 className={styles.text}>¥500/月 わーい</h2>
        </div>
      </main>
    </>
  )
}
