import Head from 'next/head'
import router from 'next/router';
import styles from '@/styles/upgrade.module.css'
import Header from '@/conponents/Header'
import PrimaryButton from '@/conponents/PrimaryButton'
import makeHaveCard from '@/utils/ok/makeHaveCard'
import type { MakeOthersCardData } from '@/types/CardData'

export default function MakeHaveCardTest() {

  const handleButton = async () => {
    console.log('button clicked');
    const data: MakeOthersCardData = {
      name: "deketa!!!!",
      organization: "test",
      x: "test",
      instagram: "test",
      others: ''
    }
    await makeHaveCard('uid', data);
    router.push('/cards');
  }

  return (
    <>
      <Head>
        <title>Who!</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <div>
          <h2 className={styles.text}>MakeHaveCardTest</h2>
        </div>
        <div style={{ width: '100%' }}>
          <PrimaryButton text={'Button'} onClick={() => handleButton()} />
        </div>
      </main>
    </>
  )
}
