import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/upgrade.module.css'
import Header from '@/conponents/Header'
import PrimaryBtn from '@/conponents/PrimaryBtn'
import AddHaveCard from '@/utils/firebase/addHaveCard'

const inter = Inter({ subsets: ['latin'] })

export default function YukaFunctionTest() {

  const handleButton = () => {
    console.log('button clicked');
    AddHaveCard()
  }

  return (
    <>
      <Head>
        <title>Who!</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <div>
          <h2 className={styles.text}>test</h2>
        </div>
        <div style={{ width: '100%' }}>
          <PrimaryBtn text={'Button'} onClick={() => handleButton()} />
        </div>
      </main>
    </>
  )
}
