import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Share.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'
import Header from '@/conponents/Header'
import QrCode2Icon from '@mui/icons-material/QrCode2';
import DisplayCard from '@/conponents/Card'
import PrimaryBtn from '@/conponents/PrimaryBtn'
import QRCode from '@/conponents/MakeQrcode'

const inter = Inter({ subsets: ['latin'] })

export default function Detail() {
  const router = useRouter();
  const cardid = router.query.cardid as string;
  const data = {
    id: "id",
    name: "ゆうか",
    organization: "watnow",
    x: "chocolatbrown",
    instagram: "yuka__matcha",
    others: "https://my-portfolio-yukachoco.vercel.app",
    urlEnabled: true,
    textColor: "#A56A7F",
    bgColor: "#F4EBEF",
    onClickHandler: () => { },
  }
  return (
    <>
      <Head>
        <title>Who!</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.list}>
          <Header useMenuIcon />
          <div className={styles.qrcode}>
            <QRCode url={`https://whooo.netlify.app/share/$%7Bdata.id%7D`}/>
            </div>
          
          <div className={styles.swipe}>
            <svg width="107" height="60" viewBox="0 0 107 60" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M53.5 0L106.761 59.25H0.239437L53.5 0Z" fill="#DCDBE8" />
            </svg>
          </div>
          <DisplayCard
            {...data}
            onClickHandler={() => {}}
          />
        </div>
        <div className={styles.returnbutton}>
          <PrimaryBtn text={'ホームに戻る'} onClick={()=>router.push("/cards")}/>
        </div>

      </main>
    </>
  )
}
